// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVpJM7uezzNB8WxrchFzhQI4fDTHmXKLU',
    appId: '1:885308111983:web:b8efaa2742865a974aa19a',
    messagingSenderId: '885308111983',
    projectId: 'infrenchprac',
    authDomain: 'infrenchprac.firebaseapp.com',
    storageBucket: 'infrenchprac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBou9l0sDaGvBuAfEAHAxpF3Bqn-zyeuAU',
    appId: '1:885308111983:android:1f7a03a37ad40b7e4aa19a',
    messagingSenderId: '885308111983',
    projectId: 'infrenchprac',
    storageBucket: 'infrenchprac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr8VMlbLijT7SH9kvyDLlKXflPlZ39FFk',
    appId: '1:885308111983:ios:e3cb129449983dd84aa19a',
    messagingSenderId: '885308111983',
    projectId: 'infrenchprac',
    storageBucket: 'infrenchprac.appspot.com',
    iosClientId: '885308111983-35f6funj4ps07f0cann8rjlpdvk098s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.infrenchprac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr8VMlbLijT7SH9kvyDLlKXflPlZ39FFk',
    appId: '1:885308111983:ios:e3cb129449983dd84aa19a',
    messagingSenderId: '885308111983',
    projectId: 'infrenchprac',
    storageBucket: 'infrenchprac.appspot.com',
    iosClientId: '885308111983-35f6funj4ps07f0cann8rjlpdvk098s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.infrenchprac',
  );
}
